### PR TITLE
Fix websocket URL and examples

### LINKED ISSUE #165: v2: No schema reference in migration guide
https://github.com/qlik-oss/enigma.js/blob/master/docs/migrate-v1.md#entry-api-changed

The above examples does not include the mandatory schema reference in the config object.

### PR DESCRIPTION
**Pull request by peol**
Fixes #165, #158

### CODE REVIEW

**Comment by peol** [comment]
These examples will be removed/rewritten/replaced later on, but they at least run now (if you have a Qlik Sense Enterprise running).

File: examples/list-apps/index.js [hunk 1]
```diff
@@ -4,41 +4,37 @@ const fs = require('fs');
 const path = require('path');
 const WebSocket = require('ws');
 const enigma = require('enigma.js');
-const qixSchema = require('./node_modules/enigma.js/schemas/12.20.0.json');
+const schema = require('./node_modules/enigma.js/schemas/12.20.0.json');
```
Comment (StefanEnberg) [inline examples/list-apps/index.js]: const schema = require('enigma.js/schemas/12.20.0.json');
