### PR TITLE
Issue #71: Error if undefined Handle passed to getApi

### LINKED ISSUE #71: Error thrown if undefined handle passed to getApi
### Description

If an undefined handle is passed into the getApi function it throws a toString not defined error.  This should either return undefined or a more appropriate error message.  

Looking at the code it seems that generally we expected a possible undefined value coming back from this call (if the api isn't found) which would be the case here.

### Steps to Reproduce

1. Use the getApi call with an 'undefined' handle

##### Expected behavior

This should return undefined as a result

##### Actual behavior

It throws an exception because handle.toString() is not defined.

### PR DESCRIPTION
**Pull request by chrismanley**
Fixes #71.

### CODE REVIEW

File: src/services/qix/api-cache.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ class ApiCache extends KeyValueCache {
   * @returns {*} The API for the handle.
   */
   getApi(handle) {
-    const entry = this.get(handle.toString());
+    const entry = handle !== undefined ? this.get(handle.toString()) : undefined;
```
Comment (peol) [inline src/services/qix/api-cache.js]: We're using `typeof foo === 'undefined'` in enigma.js
